package com.isoftstone.mybatis.entity;

import java.util.Date;
import java.util.List;

public class CgMxqz {

    private List<CgMxqmx> cgMxqmxList;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CG_MXQZ.XQBC
     *
     * @mbggenerated
     */
    private String xqbc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CG_MXQZ.JHH
     *
     * @mbggenerated
     */
    private String jhh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CG_MXQZ.CFSJ
     *
     * @mbggenerated
     */
    private Date cfsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CG_MXQZ.SFJSDD
     *
     * @mbggenerated
     */
    private String sfjsdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CG_MXQZ.XMH
     *
     * @mbggenerated
     */
    private String xmh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CG_MXQZ.LX
     *
     * @mbggenerated
     */
    private String lx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CG_MXQZ.JD
     *
     * @mbggenerated
     */
    private String jd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CG_MXQZ.SFYJS
     *
     * @mbggenerated
     */
    private String sfyjs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CG_MXQZ.JSR
     *
     * @mbggenerated
     */
    private String jsr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CG_MXQZ.JSDDSJ
     *
     * @mbggenerated
     */
    private Date jsddsj;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CG_MXQZ
     *
     * @mbggenerated
     */
    public CgMxqz(String xqbc, String jhh, Date cfsj, String sfjsdd, String xmh, String lx, String jd, String sfyjs, String jsr, Date jsddsj) {
        this.xqbc = xqbc;
        this.jhh = jhh;
        this.cfsj = cfsj;
        this.sfjsdd = sfjsdd;
        this.xmh = xmh;
        this.lx = lx;
        this.jd = jd;
        this.sfyjs = sfyjs;
        this.jsr = jsr;
        this.jsddsj = jsddsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CG_MXQZ
     *
     * @mbggenerated
     */
    public CgMxqz() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CG_MXQZ.XQBC
     *
     * @return the value of CG_MXQZ.XQBC
     *
     * @mbggenerated
     */
    public String getXqbc() {
        return xqbc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CG_MXQZ.XQBC
     *
     * @param xqbc the value for CG_MXQZ.XQBC
     *
     * @mbggenerated
     */
    public void setXqbc(String xqbc) {
        this.xqbc = xqbc == null ? null : xqbc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CG_MXQZ.JHH
     *
     * @return the value of CG_MXQZ.JHH
     *
     * @mbggenerated
     */
    public String getJhh() {
        return jhh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CG_MXQZ.JHH
     *
     * @param jhh the value for CG_MXQZ.JHH
     *
     * @mbggenerated
     */
    public void setJhh(String jhh) {
        this.jhh = jhh == null ? null : jhh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CG_MXQZ.CFSJ
     *
     * @return the value of CG_MXQZ.CFSJ
     *
     * @mbggenerated
     */
    public Date getCfsj() {
        return cfsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CG_MXQZ.CFSJ
     *
     * @param cfsj the value for CG_MXQZ.CFSJ
     *
     * @mbggenerated
     */
    public void setCfsj(Date cfsj) {
        this.cfsj = cfsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CG_MXQZ.SFJSDD
     *
     * @return the value of CG_MXQZ.SFJSDD
     *
     * @mbggenerated
     */
    public String getSfjsdd() {
        return sfjsdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CG_MXQZ.SFJSDD
     *
     * @param sfjsdd the value for CG_MXQZ.SFJSDD
     *
     * @mbggenerated
     */
    public void setSfjsdd(String sfjsdd) {
        this.sfjsdd = sfjsdd == null ? null : sfjsdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CG_MXQZ.XMH
     *
     * @return the value of CG_MXQZ.XMH
     *
     * @mbggenerated
     */
    public String getXmh() {
        return xmh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CG_MXQZ.XMH
     *
     * @param xmh the value for CG_MXQZ.XMH
     *
     * @mbggenerated
     */
    public void setXmh(String xmh) {
        this.xmh = xmh == null ? null : xmh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CG_MXQZ.LX
     *
     * @return the value of CG_MXQZ.LX
     *
     * @mbggenerated
     */
    public String getLx() {
        return lx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CG_MXQZ.LX
     *
     * @param lx the value for CG_MXQZ.LX
     *
     * @mbggenerated
     */
    public void setLx(String lx) {
        this.lx = lx == null ? null : lx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CG_MXQZ.JD
     *
     * @return the value of CG_MXQZ.JD
     *
     * @mbggenerated
     */
    public String getJd() {
        return jd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CG_MXQZ.JD
     *
     * @param jd the value for CG_MXQZ.JD
     *
     * @mbggenerated
     */
    public void setJd(String jd) {
        this.jd = jd == null ? null : jd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CG_MXQZ.SFYJS
     *
     * @return the value of CG_MXQZ.SFYJS
     *
     * @mbggenerated
     */
    public String getSfyjs() {
        return sfyjs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CG_MXQZ.SFYJS
     *
     * @param sfyjs the value for CG_MXQZ.SFYJS
     *
     * @mbggenerated
     */
    public void setSfyjs(String sfyjs) {
        this.sfyjs = sfyjs == null ? null : sfyjs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CG_MXQZ.JSR
     *
     * @return the value of CG_MXQZ.JSR
     *
     * @mbggenerated
     */
    public String getJsr() {
        return jsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CG_MXQZ.JSR
     *
     * @param jsr the value for CG_MXQZ.JSR
     *
     * @mbggenerated
     */
    public void setJsr(String jsr) {
        this.jsr = jsr == null ? null : jsr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CG_MXQZ.JSDDSJ
     *
     * @return the value of CG_MXQZ.JSDDSJ
     *
     * @mbggenerated
     */
    public Date getJsddsj() {
        return jsddsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CG_MXQZ.JSDDSJ
     *
     * @param jsddsj the value for CG_MXQZ.JSDDSJ
     *
     * @mbggenerated
     */
    public void setJsddsj(Date jsddsj) {
        this.jsddsj = jsddsj;
    }

    @Override
    public String toString() {
        return "CgMxqz{" +
                "cgMxqmxList=" + cgMxqmxList +
                ", xqbc='" + xqbc + '\'' +
                ", jhh='" + jhh + '\'' +
                ", cfsj=" + cfsj +
                ", sfjsdd='" + sfjsdd + '\'' +
                ", xmh='" + xmh + '\'' +
                ", lx='" + lx + '\'' +
                ", jd='" + jd + '\'' +
                ", sfyjs='" + sfyjs + '\'' +
                ", jsr='" + jsr + '\'' +
                ", jsddsj=" + jsddsj +
                '}';
    }

    public List<CgMxqmx> getCgMxqmxList() {
        return cgMxqmxList;
    }

    public void setCgMxqmxList(List<CgMxqmx> cgMxqmxList) {
        this.cgMxqmxList = cgMxqmxList;
    }
}