package com.isoftstone.mybatis.entity;

import java.math.BigDecimal;

public class CgMxqmx{

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CG_MXQMX.XQBC
     *
     * @mbggenerated
     */
    private String xqbc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CG_MXQMX.MXQHH
     *
     * @mbggenerated
     */
    private String mxqhh;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CG_MXQMX.JHH
     *
     * @mbggenerated
     */
    private String jhh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CG_MXQMX.USERCENTER
     *
     * @mbggenerated
     */
    private String usercenter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CG_MXQMX.WLBM
     *
     * @mbggenerated
     */
    private String wlbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CG_MXQMX.XHSL
     *
     * @mbggenerated
     */
    private BigDecimal xhsl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CG_MXQMX.ZPLX
     *
     * @mbggenerated
     */
    private String zplx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CG_MXQMX.JBDW
     *
     * @mbggenerated
     */
    private String jbdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CG_MXQMX.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CG_MXQMX.JSBS
     *
     * @mbggenerated
     */
    private String jsbs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CG_MXQMX.CX
     *
     * @mbggenerated
     */
    private String cx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CG_MXQMX.YWLBM
     *
     * @mbggenerated
     */
    private String ywlbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CG_MXQMX.JEH
     *
     * @mbggenerated
     */
    private String jeh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CG_MXQMX.SCXB
     *
     * @mbggenerated
     */
    private String scxb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CG_MXQMX.WLMC
     *
     * @mbggenerated
     */
    private String wlmc;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CG_MXQMX
     *
     * @mbggenerated
     */
    public CgMxqmx(String xqbc, String mxqhh, String jhh, String usercenter, String wlbm, BigDecimal xhsl, String zplx, String jbdw, String status, String jsbs, String cx, String ywlbm, String jeh, String scxb, String wlmc) {
        this.xqbc = xqbc;
        this.mxqhh = mxqhh;
        this.jhh = jhh;
        this.usercenter = usercenter;
        this.wlbm = wlbm;
        this.xhsl = xhsl;
        this.zplx = zplx;
        this.jbdw = jbdw;
        this.status = status;
        this.jsbs = jsbs;
        this.cx = cx;
        this.ywlbm = ywlbm;
        this.jeh = jeh;
        this.scxb = scxb;
        this.wlmc = wlmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CG_MXQMX
     *
     * @mbggenerated
     */
    public CgMxqmx() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CG_MXQMX.JHH
     *
     * @return the value of CG_MXQMX.JHH
     *
     * @mbggenerated
     */
    public String getJhh() {
        return jhh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CG_MXQMX.JHH
     *
     * @param jhh the value for CG_MXQMX.JHH
     *
     * @mbggenerated
     */
    public void setJhh(String jhh) {
        this.jhh = jhh == null ? null : jhh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CG_MXQMX.USERCENTER
     *
     * @return the value of CG_MXQMX.USERCENTER
     *
     * @mbggenerated
     */
    public String getUsercenter() {
        return usercenter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CG_MXQMX.USERCENTER
     *
     * @param usercenter the value for CG_MXQMX.USERCENTER
     *
     * @mbggenerated
     */
    public void setUsercenter(String usercenter) {
        this.usercenter = usercenter == null ? null : usercenter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CG_MXQMX.WLBM
     *
     * @return the value of CG_MXQMX.WLBM
     *
     * @mbggenerated
     */
    public String getWlbm() {
        return wlbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CG_MXQMX.WLBM
     *
     * @param wlbm the value for CG_MXQMX.WLBM
     *
     * @mbggenerated
     */
    public void setWlbm(String wlbm) {
        this.wlbm = wlbm == null ? null : wlbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CG_MXQMX.XHSL
     *
     * @return the value of CG_MXQMX.XHSL
     *
     * @mbggenerated
     */
    public BigDecimal getXhsl() {
        return xhsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CG_MXQMX.XHSL
     *
     * @param xhsl the value for CG_MXQMX.XHSL
     *
     * @mbggenerated
     */
    public void setXhsl(BigDecimal xhsl) {
        this.xhsl = xhsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CG_MXQMX.ZPLX
     *
     * @return the value of CG_MXQMX.ZPLX
     *
     * @mbggenerated
     */
    public String getZplx() {
        return zplx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CG_MXQMX.ZPLX
     *
     * @param zplx the value for CG_MXQMX.ZPLX
     *
     * @mbggenerated
     */
    public void setZplx(String zplx) {
        this.zplx = zplx == null ? null : zplx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CG_MXQMX.JBDW
     *
     * @return the value of CG_MXQMX.JBDW
     *
     * @mbggenerated
     */
    public String getJbdw() {
        return jbdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CG_MXQMX.JBDW
     *
     * @param jbdw the value for CG_MXQMX.JBDW
     *
     * @mbggenerated
     */
    public void setJbdw(String jbdw) {
        this.jbdw = jbdw == null ? null : jbdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CG_MXQMX.STATUS
     *
     * @return the value of CG_MXQMX.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CG_MXQMX.STATUS
     *
     * @param status the value for CG_MXQMX.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CG_MXQMX.JSBS
     *
     * @return the value of CG_MXQMX.JSBS
     *
     * @mbggenerated
     */
    public String getJsbs() {
        return jsbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CG_MXQMX.JSBS
     *
     * @param jsbs the value for CG_MXQMX.JSBS
     *
     * @mbggenerated
     */
    public void setJsbs(String jsbs) {
        this.jsbs = jsbs == null ? null : jsbs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CG_MXQMX.CX
     *
     * @return the value of CG_MXQMX.CX
     *
     * @mbggenerated
     */
    public String getCx() {
        return cx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CG_MXQMX.CX
     *
     * @param cx the value for CG_MXQMX.CX
     *
     * @mbggenerated
     */
    public void setCx(String cx) {
        this.cx = cx == null ? null : cx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CG_MXQMX.YWLBM
     *
     * @return the value of CG_MXQMX.YWLBM
     *
     * @mbggenerated
     */
    public String getYwlbm() {
        return ywlbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CG_MXQMX.YWLBM
     *
     * @param ywlbm the value for CG_MXQMX.YWLBM
     *
     * @mbggenerated
     */
    public void setYwlbm(String ywlbm) {
        this.ywlbm = ywlbm == null ? null : ywlbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CG_MXQMX.JEH
     *
     * @return the value of CG_MXQMX.JEH
     *
     * @mbggenerated
     */
    public String getJeh() {
        return jeh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CG_MXQMX.JEH
     *
     * @param jeh the value for CG_MXQMX.JEH
     *
     * @mbggenerated
     */
    public void setJeh(String jeh) {
        this.jeh = jeh == null ? null : jeh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CG_MXQMX.SCXB
     *
     * @return the value of CG_MXQMX.SCXB
     *
     * @mbggenerated
     */
    public String getScxb() {
        return scxb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CG_MXQMX.SCXB
     *
     * @param scxb the value for CG_MXQMX.SCXB
     *
     * @mbggenerated
     */
    public void setScxb(String scxb) {
        this.scxb = scxb == null ? null : scxb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CG_MXQMX.WLMC
     *
     * @return the value of CG_MXQMX.WLMC
     *
     * @mbggenerated
     */
    public String getWlmc() {
        return wlmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CG_MXQMX.WLMC
     *
     * @param wlmc the value for CG_MXQMX.WLMC
     *
     * @mbggenerated
     */
    public void setWlmc(String wlmc) {
        this.wlmc = wlmc == null ? null : wlmc.trim();
    }

    public String getXqbc() {
        return xqbc;
    }

    @Override
    public String toString() {
        return "CgMxqmx{" +
                "xqbc='" + xqbc + '\'' +
                ", mxqhh='" + mxqhh + '\'' +
                ", jhh='" + jhh + '\'' +
                ", usercenter='" + usercenter + '\'' +
                ", wlbm='" + wlbm + '\'' +
                ", xhsl=" + xhsl +
                ", zplx='" + zplx + '\'' +
                ", jbdw='" + jbdw + '\'' +
                ", status='" + status + '\'' +
                ", jsbs='" + jsbs + '\'' +
                ", cx='" + cx + '\'' +
                ", ywlbm='" + ywlbm + '\'' +
                ", jeh='" + jeh + '\'' +
                ", scxb='" + scxb + '\'' +
                ", wlmc='" + wlmc + '\'' +
                '}';
    }

    public void setXqbc(String xqbc) {
        this.xqbc = xqbc;
    }

    public String getMxqhh() {
        return mxqhh;
    }

    public void setMxqhh(String mxqhh) {
        this.mxqhh = mxqhh;
    }
}