package com.isoftstone.mybatis.mapper;

import com.isoftstone.mybatis.entity.CgMxqz;

public interface CgMxqzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CG_MXQZ
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String xqbc);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CG_MXQZ
     *
     * @mbggenerated
     */
    int insert(CgMxqz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CG_MXQZ
     *
     * @mbggenerated
     */
    int insertSelective(CgMxqz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CG_MXQZ
     *
     * @mbggenerated
     */
    CgMxqz selectByPrimaryKey(String xqbc);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CG_MXQZ
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CgMxqz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CG_MXQZ
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CgMxqz record);
}