package com.isoftstone.mybatis.mapper;

import com.isoftstone.mybatis.entity.CgMxqmx;

public interface CgMxqmxMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CG_MXQMX
     *
     * @mbggenerated
     */
    int insert(CgMxqmx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CG_MXQMX
     *
     * @mbggenerated
     */
    int insertSelective(CgMxqmx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CG_MXQMX
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CgMxqmx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CG_MXQMX
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CgMxqmx record);
}